"""Supplementary CET-4 vocabulary data (words 41-200).

Compact tuple format:
(word, phonetic, pos, meaning_cn, rank, example, colloc, syn, confusable)
"""

CET4_WORDS_EXTENDED = [
    ("alter", "/ˈɔːltə/", "v.", "改变；修改", 41, "Nothing can alter the fact.",
     ["alter the course", "alter dramatically"], ["change", "modify", "adjust"], ["altar"]),
    ("alternative", "/ɔːlˈtɜːnətɪv/", "n./adj.", "替代选择；可替代的", 42, "We need to find an alternative solution.",
     ["alternative energy", "have no alternative"], ["option", "choice", "substitute"], []),
    ("amaze", "/əˈmeɪz/", "v.", "使惊奇；使惊愕", 43, "Her performance amazed the audience.",
     ["be amazed at", "amaze everyone"], ["astonish", "surprise", "astound"], []),
    ("ambition", "/æmˈbɪʃn/", "n.", "野心；雄心；抱负", 44, "She has the ambition to become CEO.",
     ["political ambition", "achieve one's ambition"], ["aspiration", "drive", "goal"], []),
    ("amount", "/əˈmaʊnt/", "n.", "数量；总额", 45, "A large amount of money was donated.",
     ["a large amount of", "the total amount"], ["quantity", "sum", "volume"], ["number"]),
    ("analysis", "/əˈnæləsɪs/", "n.", "分析", 46, "The data requires careful analysis.",
     ["data analysis", "in the final analysis"], ["examination", "evaluation", "study"], []),
    ("ancestor", "/ˈænsestə/", "n.", "祖先；祖宗", 47, "My ancestors came from Ireland.",
     ["common ancestor", "ancestor worship"], ["forefather", "forebear", "predecessor"], ["descendant"]),
    ("angle", "/ˈæŋɡl/", "n.", "角；角度；观点", 48, "Let's look at this from another angle.",
     ["right angle", "from a different angle"], ["perspective", "viewpoint", "corner"], ["angel"]),
    ("anniversary", "/ˌænɪˈvɜːsəri/", "n.", "周年纪念日", 49, "They celebrated their 10th wedding anniversary.",
     ["wedding anniversary", "anniversary celebration"], [], []),
    ("announce", "/əˈnaʊns/", "v.", "宣布；宣告", 50, "The president announced his resignation.",
     ["announce plans", "officially announce"], ["declare", "proclaim", "state"], ["denounce"]),
    ("annual", "/ˈænjuəl/", "adj.", "年度的；每年的", 51, "The company published its annual report.",
     ["annual meeting", "annual income", "annual report"], ["yearly"], []),
    ("anxiety", "/æŋˈzaɪəti/", "n.", "焦虑；担心", 52, "She felt anxiety about the exam results.",
     ["anxiety disorder", "social anxiety", "reduce anxiety"], ["worry", "unease", "nervousness"], ["calm"]),
    ("apart", "/əˈpɑːt/", "adv.", "分开；分离；相距", 53, "The two houses are 50 meters apart.",
     ["apart from", "fall apart", "tell apart"], ["separately", "aside", "away"], ["together"]),
    ("apparent", "/əˈpærənt/", "adj.", "明显的；表面上的", 54, "It became apparent that she was lying.",
     ["for no apparent reason", "become apparent"], ["obvious", "evident", "clear"], ["obscure"]),
    ("appeal", "/əˈpiːl/", "n./v.", "呼吁；吸引；上诉", 55, "The charity launched an appeal for donations.",
     ["appeal to", "appeal against", "mass appeal"], ["attract", "request", "petition"], []),
    ("appearance", "/əˈpɪərəns/", "n.", "外貌；出现", 56, "Don't judge by appearance alone.",
     ["physical appearance", "make an appearance", "in appearance"], ["look", "aspect", "presence"], ["disappearance"]),
    ("appetite", "/ˈæpɪtaɪt/", "n.", "食欲；胃口；欲望", 57, "Exercise gave her a healthy appetite.",
     ["appetite for", "loss of appetite", "risk appetite"], ["hunger", "desire", "craving"], []),
    ("appliance", "/əˈplaɪəns/", "n.", "电器；器具", 58, "The kitchen is full of modern appliances.",
     ["household appliance", "electrical appliance"], ["device", "gadget", "machine"], []),
    ("application", "/ˌæplɪˈkeɪʃn/", "n.", "申请；应用", 59, "I submitted my job application online.",
     ["job application", "practical application", "application form"], ["request", "use", "software"], []),
    ("apply", "/əˈplaɪ/", "v.", "申请；应用；适用", 60, "This rule doesn't apply to you.",
     ["apply for", "apply to", "apply oneself"], ["request", "use", "be relevant"], []),
    ("appoint", "/əˈpɔɪnt/", "v.", "任命；指定", 61, "She was appointed as the new director.",
     ["appoint as", "appoint a committee"], ["designate", "assign", "name"], ["disappoint"]),
    ("appreciate", "/əˈpriːʃieɪt/", "v.", "感激；欣赏；升值", 62, "I really appreciate your help.",
     ["appreciate the value", "greatly appreciate"], ["value", "acknowledge", "admire"], ["depreciate"]),
    ("approach", "/əˈprəʊtʃ/", "v./n.", "接近；方法", 63, "A new approach to teaching is needed.",
     ["approach to", "take an approach", "innovative approach"], ["method", "way", "strategy"], []),
    ("appropriate", "/əˈprəʊpriət/", "adj.", "适当的；合适的", 64, "Is this an appropriate time to call?",
     ["appropriate for", "appropriate behavior"], ["suitable", "proper", "fitting"], ["inappropriate"]),
    ("approve", "/əˈpruːv/", "v.", "批准；认可", 65, "The committee approved the proposal.",
     ["approve of", "officially approve"], ["endorse", "authorize", "agree"], ["disapprove", "reject"]),
    ("arise", "/əˈraɪz/", "v.", "出现；产生", 66, "Problems arose during the construction.",
     ["arise from", "should the need arise"], ["emerge", "appear", "occur"], []),
    ("arrange", "/əˈreɪndʒ/", "v.", "安排；排列", 67, "Can you arrange a meeting for Friday?",
     ["arrange for", "arrange with"], ["organize", "plan", "set up"], ["disarrange"]),
    ("arrest", "/əˈrest/", "v./n.", "逮捕；阻止", 68, "The suspect was arrested yesterday.",
     ["under arrest", "house arrest", "arrest the decline"], ["detain", "capture", "seize"], ["release"]),
    ("article", "/ˈɑːtɪkl/", "n.", "文章；物品；冠词", 69, "She wrote an article about climate change.",
     ["article on", "definite article", "news article"], ["essay", "piece", "item"], []),
    ("artificial", "/ˌɑːtɪˈfɪʃl/", "adj.", "人工的；人造的；假的", 70, "The flowers were artificial but looked real.",
     ["artificial intelligence", "artificial light", "artificial sweetener"], ["synthetic", "man-made", "fake"], ["natural"]),
    ("aspect", "/ˈæspekt/", "n.", "方面；层面", 71, "Consider every aspect of the problem.",
     ["aspect of", "important aspect", "from every aspect"], ["facet", "side", "dimension"], []),
    ("assemble", "/əˈsembl/", "v.", "集合；组装", 72, "The students assembled in the hall.",
     ["assemble a team", "assemble parts"], ["gather", "collect", "put together"], ["disperse", "disassemble"]),
    ("assess", "/əˈses/", "v.", "评估；评定", 73, "We need to assess the situation first.",
     ["assess the damage", "assess the risk"], ["evaluate", "judge", "estimate"], []),
    ("asset", "/ˈæset/", "n.", "资产；优点", 74, "Her experience is a valuable asset to the team.",
     ["financial asset", "valuable asset", "fixed asset"], ["resource", "advantage", "property"], ["liability"]),
    ("assign", "/əˈsaɪn/", "v.", "分配；指派", 75, "Each student was assigned a research topic.",
     ["assign to", "assign a task", "assign responsibility"], ["allocate", "designate", "appoint"], []),
    ("assist", "/əˈsɪst/", "v.", "帮助；协助", 76, "Can I assist you with anything?",
     ["assist in", "assist with"], ["help", "aid", "support"], ["hinder"]),
    ("associate", "/əˈsəʊʃieɪt/", "v./n.", "联系；关联；同事", 77, "People often associate wealth with happiness.",
     ["associate with", "business associate"], ["link", "connect", "relate"], ["dissociate"]),
    ("assume", "/əˈsjuːm/", "v.", "假设；承担", 78, "We can't assume that everyone agrees.",
     ["assume responsibility", "assume that"], ["presume", "suppose", "take on"], []),
    ("atmosphere", "/ˈætməsfɪə/", "n.", "气氛；大气", 79, "The restaurant has a romantic atmosphere.",
     ["friendly atmosphere", "the earth's atmosphere", "create an atmosphere"], ["environment", "mood", "air"], []),
    ("attach", "/əˈtætʃ/", "v.", "附上；连接；重视", 80, "Please attach the file to your email.",
     ["attach to", "attach importance to", "attach a label"], ["fasten", "connect", "join"], ["detach"]),
    ("attempt", "/əˈtempt/", "n./v.", "尝试；企图", 81, "He made an attempt to break the record.",
     ["attempt to", "make an attempt", "suicide attempt"], ["try", "effort", "endeavor"], []),
    ("attend", "/əˈtend/", "v.", "参加；出席；注意", 82, "Will you attend the conference?",
     ["attend a meeting", "attend to", "attend school"], ["be present at", "go to", "take part in"], ["absent"]),
    ("attitude", "/ˈætɪtjuːd/", "n.", "态度；看法", 83, "A positive attitude helps in difficult times.",
     ["positive attitude", "attitude towards", "change your attitude"], ["mindset", "outlook", "approach"], []),
    ("attract", "/əˈtrækt/", "v.", "吸引；引起", 84, "The exhibition attracted thousands of visitors.",
     ["attract attention", "attract investment", "attract tourists"], ["draw", "appeal to", "lure"], ["repel"]),
    ("attribute", "/əˈtrɪbjuːt/", "v./n.", "归因于；属性", 85, "He attributes his success to hard work.",
     ["attribute to", "positive attribute", "key attribute"], ["ascribe", "credit", "quality"], []),
    ("authority", "/ɔːˈθɒrəti/", "n.", "权威；当局；权力", 86, "The local authority approved the plan.",
     ["local authority", "have the authority", "in authority"], ["power", "jurisdiction", "expert"], []),
    ("available", "/əˈveɪləbl/", "adj.", "可用的；可获得的", 87, "Is this seat available?",
     ["make available", "readily available", "available for"], ["accessible", "obtainable", "free"], ["unavailable"]),
    ("average", "/ˈævərɪdʒ/", "n./adj.", "平均；普通的", 88, "The average temperature this month is 20°C.",
     ["on average", "above average", "national average"], ["mean", "typical", "normal"], ["exceptional"]),
    ("avoid", "/əˈvɔɪd/", "v.", "避免；回避", 89, "Try to avoid making the same mistake.",
     ["avoid doing", "avoid confrontation", "avoid at all costs"], ["evade", "stay away from", "prevent"], ["face", "confront"]),
    ("award", "/əˈwɔːd/", "n./v.", "奖；授予", 90, "She won the award for best actress.",
     ["win an award", "present an award", "award a contract"], ["prize", "honor", "grant"], []),
    ("aware", "/əˈweə/", "adj.", "意识到的；知道的", 91, "Are you aware of the risks?",
     ["be aware of", "become aware", "environmentally aware"], ["conscious", "mindful", "informed"], ["unaware", "ignorant"]),
    ("balance", "/ˈbæləns/", "n./v.", "平衡；余额", 92, "A good diet requires a balance of nutrients.",
     ["strike a balance", "work-life balance", "bank balance"], ["equilibrium", "stability", "harmony"], ["imbalance"]),
    ("ban", "/bæn/", "v./n.", "禁止；禁令", 93, "Smoking is banned in public places.",
     ["ban on", "impose a ban", "lift the ban"], ["prohibit", "forbid", "outlaw"], ["allow", "permit"]),
    ("barrier", "/ˈbæriə/", "n.", "障碍；屏障", 94, "Language can be a barrier to communication.",
     ["language barrier", "break down barriers", "trade barrier"], ["obstacle", "block", "hindrance"], []),
    ("basic", "/ˈbeɪsɪk/", "adj.", "基本的；基础的", 95, "Food and shelter are basic needs.",
     ["basic principle", "basic knowledge", "basic right"], ["fundamental", "elementary", "essential"], ["advanced"]),
    ("basis", "/ˈbeɪsɪs/", "n.", "基础；根据", 96, "We meet on a weekly basis.",
     ["on a regular basis", "on the basis of", "form the basis"], ["foundation", "ground", "base"], []),
    ("bear", "/beə/", "v.", "忍受；承担；生育", 97, "I can't bear the pain anymore.",
     ["bear in mind", "bear responsibility", "bear fruit"], ["endure", "tolerate", "carry"], []),
    ("behavior", "/bɪˈheɪvjə/", "n.", "行为；举止", 98, "His behavior at the party was unacceptable.",
     ["good behavior", "antisocial behavior", "consumer behavior"], ["conduct", "actions", "manners"], []),
    ("belief", "/bɪˈliːf/", "n.", "信念；信仰", 99, "She has a strong belief in justice.",
     ["religious belief", "popular belief", "beyond belief"], ["conviction", "faith", "opinion"], ["disbelief"]),
    ("belong", "/bɪˈlɒŋ/", "v.", "属于；归属", 100, "This book belongs to me.",
     ["belong to", "a sense of belonging"], ["be owned by", "be part of", "fit in"], []),
]

# Shorthand export for tests
CET4_WORDS = CET4_WORDS_EXTENDED
